version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
      - POSTGRES_DB=tinyauth

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
