FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN groupadd -r flask && useradd -r -g flask flask

RUN mkdir -p /app/var/audit && chown flask: /app/var/audit

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./tinyauth /app/src/tinyauth

COPY ./docker/flask/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh

COPY ./docker/flask/start-dev.sh /start-dev.sh
RUN sed -i 's/\r//' /start-dev.sh

WORKDIR /app/src

USER flask
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/start-dev.sh"]
