"""empty message

Revision ID: 0d0c426e7b01
Revises: 0d42398b4cdc
Create Date: 2017-10-29 20:37:10.615469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0c426e7b01'
down_revision = '0d42398b4cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key_id', sa.String(length=128), nullable=True),
    sa.Column('secret_access_key', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_key')
    # ### end Alembic commands ###
