"""empty message

Revision ID: 12a89fe95b4b
Revises: 2bdeca01ff1c
Create Date: 2018-08-11 10:12:13.574031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a89fe95b4b'
down_revision = '2bdeca01ff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('public_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_authn_credential', 'public_key')
    # ### end Alembic commands ###
