"""empty message

Revision ID: 1ba11c6355bf
Revises: 57ed8e7c989f
Create Date: 2018-08-11 08:20:01.798322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba11c6355bf'
down_revision = '57ed8e7c989f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('public_key', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'web_authn_credential', ['public_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_authn_credential', type_='unique')
    op.drop_column('web_authn_credential', 'public_key')
    # ### end Alembic commands ###
