"""empty message

Revision ID: 2bdeca01ff1c
Revises: cc2fa4542c97
Create Date: 2018-08-11 10:12:00.810925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdeca01ff1c'
down_revision = 'cc2fa4542c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_authn_credential', 'public_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('public_key', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
