"""empty message

Revision ID: 5981b5d68f85
Revises: fba82ca98a41
Create Date: 2018-08-11 07:59:29.236042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5981b5d68f85'
down_revision = 'fba82ca98a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('public_key', sa.String(length=65), nullable=True))
    op.create_unique_constraint(None, 'web_authn_credential', ['public_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_authn_credential', type_='unique')
    op.drop_column('web_authn_credential', 'public_key')
    # ### end Alembic commands ###
