"""empty message

Revision ID: 7db3f3cca1a9
Revises: 0d0c426e7b01
Create Date: 2017-10-31 16:06:04.780249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db3f3cca1a9'
down_revision = '0d0c426e7b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy', sa.Column('policy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy', 'policy')
    # ### end Alembic commands ###
