"""empty message

Revision ID: 840ba6d53964
Revises: a93b0a674015
Create Date: 2018-08-04 20:08:53.846627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840ba6d53964'
down_revision = 'a93b0a674015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_authn_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=250), nullable=False),
    sa.Column('pub_key', sa.String(length=65), nullable=True),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('pub_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_authn_credential')
    # ### end Alembic commands ###
