"""empty message

Revision ID: a93b0a674015
Revises: e5e4c9e77c33
Create Date: 2017-11-23 14:17:38.145406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b0a674015'
down_revision = 'e5e4c9e77c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('salt', sa.LargeBinary(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
