"""empty message

Revision ID: cc2fa4542c97
Revises: 1ba11c6355bf
Create Date: 2018-08-11 10:10:18.998068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2fa4542c97'
down_revision = '1ba11c6355bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('web_authn_credential_public_key_key', 'web_authn_credential', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('web_authn_credential_public_key_key', 'web_authn_credential', ['public_key'])
    # ### end Alembic commands ###
