"""empty message

Revision ID: e5e4c9e77c33
Revises: 9efdb5e1f6fb
Create Date: 2017-11-16 13:45:35.581783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5e4c9e77c33'
down_revision = '9efdb5e1f6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('policy', sa.Variant(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('policy', sa.Variant(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_policies')
    op.drop_table('group_policies')
    op.drop_table('policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('policy_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='policy_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('group_policies',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_policies_group_id_fkey'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], name='group_policies_policy_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'policy_id', name='group_policies_pkey')
    )
    op.create_table('user_policies',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], name='user_policies_policy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_policies_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'policy_id', name='user_policies_pkey')
    )
    op.drop_table('user_policy')
    op.drop_table('group_policy')
    # ### end Alembic commands ###
