"""empty message

Revision ID: fba82ca98a41
Revises: 840ba6d53964
Create Date: 2018-08-05 12:06:06.537276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba82ca98a41'
down_revision = '840ba6d53964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_constraint('web_authn_credential_pub_key_key', 'web_authn_credential', type_='unique')
    op.drop_column('web_authn_credential', 'pub_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_authn_credential', sa.Column('pub_key', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    op.create_unique_constraint('web_authn_credential_pub_key_key', 'web_authn_credential', ['pub_key'])
    op.drop_column('web_authn_credential', 'name')
    # ### end Alembic commands ###
